/*********************************************************
       Code Generated By  .  .  .  .  Delaney's Script Bot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Version.  .  .  .  .  .  .  .  10.0.0.14
       Build  .  .  .  .  .  .  .  .  20191113 216
       Template Name.  .  .  .  .  .  Project Green 2.0
       Template Version.  .  .  .  .  20191111 001
       Author .  .  .  .  .  .  .  .  Delaney

                          .___,
                       ___('v')___
                       `"-\._./-"'
                           ^ ^

 *********************************************************/

using System.Collections.Generic;


namespace Delaney.Models
{
    public partial class Summary<TEntity>
    {
        public IEnumerable<TEntity> Models { get; set; }

        public TEntity Selected { get; set; }

        /// <summary>
        /// The total number of records
        /// </summary>       
        public int Count { get; set; }

        public string Search { get; set; }

        /// <summary>
        /// The result is divided into groups of n record.
        /// This is a list of groups.
        /// </summary>
        public IEnumerable<int> Groups { get; set; }
    }
}