/*********************************************************
       Code Generated By  .  .  .  .  Delaney's Script Bot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Version.  .  .  .  .  .  .  .  10.0.0.14 
       Build  .  .  .  .  .  .  .  .  20191113 216
       Template Name.  .  .  .  .  .  Project Green 2.0
       Template Version.  .  .  .  .  20191111 001
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '
 
 
 *********************************************************/

namespace Delaney
{
    public partial class Settings
    {
        #region General Setting
        public static string DateFormatLong { get; private set; } = "dd MMM yyyy";
        public static string DateFormatShort { get; private set; } = "yyyy-MM-dd";
        public static string ApplicationName { get; private set; } = "PayPal Smart Button Test";

        public static string Version
        {
            get
            {
                System.Reflection.Assembly assembly =
                    System.Reflection.Assembly.GetExecutingAssembly();

                System.Diagnostics.FileVersionInfo fileVersionInfo =
                    System.Diagnostics.FileVersionInfo.GetVersionInfo(assembly.Location);

                string version =
                    fileVersionInfo.FileVersion;

                return version;
            }
        }

        public static string VersionString
        {
            get
            {
                return "Version " + Version;
            }
        }
        #endregion
    }
}