/*********************************************************
       Code Generated By  .  .  .  .  Delaney's Script Bot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Version.  .  .  .  .  .  .  .  10.0.0.14 
       Build  .  .  .  .  .  .  .  .  20191113 216
       Template Name.  .  .  .  .  .  Project Green 2.0
       Template Version.  .  .  .  .  20200320 003
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '

*********************************************************/

using System;
using System.Collections.Generic;

namespace Delaney.Services.Data.Core
{
    public partial interface IUnitOfWork : IDisposable
    {
        static bool Commit { get; set; }

        Repositories.IBasketRepository Baskets { get; }
        Repositories.IInvoiceRepository Invoices { get; }
        Repositories.IProductRepository Products { get; }

        void GetProducts(Core.Domain.Basket basket);
        void GetBasket(Core.Domain.Product product);

        void Add(Core.Domain.Basket core);
        void Add(IEnumerable<Core.Domain.Basket> cores);
        void Add(Core.Domain.Invoice core);
        void Add(IEnumerable<Core.Domain.Invoice> cores);
        void Add(Core.Domain.Product core);
        void Add(IEnumerable<Core.Domain.Product> cores);

        DataStoreResult Delete(IEnumerable<Core.Domain.Product> products);

        DataStoreResult Delete(Core.Domain.Product product);

        DataStoreResult Complete();
    }
}