/*********************************************************
       Code Generated By  .  .  .  .  Delaney's Script Bot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Version.  .  .  .  .  .  .  .  10.0.0.14 
       Build  .  .  .  .  .  .  .  .  20191113 216
       Template Name.  .  .  .  .  .  Project Green 2.0
       Template Version.  .  .  .  .  20191030 001
       Author .  .  .  .  .  .  .  .  Delaney
       
                          .___,
                       ___('v')___
                       `"-\._./-"'
                           ^ ^

*********************************************************/

using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Delaney.Services.Data.Core.Domain
{
    public abstract class Abstract
    {
        private string _guid;
        public string GUID 
        { 
            get
            {
                if(string.IsNullOrEmpty(_guid))
                    _guid = System.Guid.NewGuid().ToString();                    

                return _guid;
            }
            set
            {
                _guid = value;
            }
        }
        


        #region CreatedDate
        // This is applied on save
        protected DateTime? _createdDate;
        public DateTime? CreatedDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                if (_createdDate != value)
                {
                    _createdDate = value;
                    IsSaved = false;
                }
            }
        }
        #endregion

        [IgnoreDataMember]
        [XmlIgnore]
        public string CreatedDateString
        {
            get
            {
                return CreatedDate?.ToString(Settings.DateFormatShort);
            }
        }



        // This is applied on save
        [IgnoreDataMember]
        [XmlIgnore]
        public bool IsSaved { get; set; } = true;

        public abstract void Update(Abstract entity);
    }
}