/*********************************************************
       Code Generated By  .  .  .  .  Delaney's Script Bot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Version.  .  .  .  .  .  .  .  10.0.0.14 
       Build  .  .  .  .  .  .  .  .  20191113 216
       Template Name.  .  .  .  .  .  Project Green 2.0
       Template Version.  .  .  .  .  20200529 002
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '

 *********************************************************/

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delaney.Areas.Controllers
{
    public partial class InvoiceController : Delaney.Controllers.Abstract
    {
        public InvoiceController(Delaney.Services.Data.Core.IUnitOfWork unitOfWork) : base(unitOfWork) {}


        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                IEnumerable<Services.Data.Core.Domain.Invoice> invoices = null;

                invoices = _unitOfWork.Invoices.GetAll();

                var Models = new List<Models.Invoice>();

                if(invoices != null)
                    foreach(var invoice in invoices)
                    {
                        var model = new Models.Invoice(invoice);
                        Models.Add(model);
                    }

                var summary = new Models.Summary<Models.Invoice>
                {
                    Models = Models,
                    Count = Models.Count,
                };
                
                return View(summary);
            }
            catch (System.Exception ex)
            {
                ModelState.AddModelError(
                        "Error",
                        ex.Message);
                
                return View();
            }
        }

        [HttpGet]
        public IActionResult Detail (int? id)
        {
            if (id == null)
                return Redirect("~/invoice");

            var invoice = _unitOfWork.Invoices.Get((int)id);

            if (invoice == null)
                return Redirect(
                    "/../Invoice");
            else
            {
                var model = new Models.Invoice(invoice);
                
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Delete (int? id)
        {
            if (id == null)
                return Redirect("~/invoice");

            var invoice = _unitOfWork.Invoices.Get(id);

            if (invoice == null)
                return Redirect("/../Invoice");
            else
            {
                var model = new Models.Invoice(invoice);

                return View(model);
            }
        }
        [HttpPost]
        public IActionResult Delete(Models.Invoice model)
        {
            if (ModelState.IsValid)
            {
                if(model == null)
                    return View(model);

                if(model.Id == null)
                    return View(model);

                try
                {
                    if (_unitOfWork.Invoices
                                   .Remove((int)model.Id) != Services.Data.DataStoreResult.Success)
                    {
                        ModelState.AddModelError("Error",
                                                 "Could not remove record.");
                        return View(model);
                    }
                

                    _unitOfWork.Complete();

                    return Redirect(
                        "/../Invoice");
                }
                catch
                {
                    ModelState.AddModelError("Error",
                                             "Cannot delete the Invoice.");

                    return View(model);
                }
            }
            else
                return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int? Id)
        {
            Services.Data.Core.Domain.Invoice invoice;

            if (Id == null)
                invoice = new Services.Data.Core.Domain.Invoice();
            else
            {
                invoice = _unitOfWork.Invoices.Get((int)Id);

                if (invoice == null)
                    return Redirect(
                        "/../Invoice");
            }

            var model = new Models.Invoice(invoice);

            // Model parents and children
            //model.PopulateChilden();

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Models.Invoice model)
        {
            if (model != null)
            {
                // Temporary remove many to many selected collections,
                // as they will cause invalid model state if there are any required fields on the many to many selected.
                ModelState.Clear();
                TryValidateModel(model);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if(!model.Validate(_unitOfWork,
                                       out List<string> errors))
                    {
                        foreach(var error in errors)
                        {
                            ModelState.AddModelError(
                                "Error",
                                error);
                        }

                        return View(model);
                    }

                    _unitOfWork.Invoices.Add(model.GetCore());
                    if(_unitOfWork.Complete() == Services.Data.DataStoreResult.Success)
                        return Redirect(
                            "/../Invoice");

                    return View(model);
                }
                catch (System.Exception ex)
                {
                    ModelState.AddModelError(
                        "Error",
                        ex.Message);

                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        public IActionResult Cancel()
        {
            return Redirect(
                "/../Invoice");
        }
    }
}